services: 
  app:
    build: ./app/
    image: career-prediction-app:latest
    container_name: career-prediction-app
    env_file:
    - .env
    depends_on:
      - rabbitmq
      - database
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - ./app:/app
    restart: unless-stopped
    ports:
      - "8080:8080"

  web-proxy:
    image: nginx:latest
    container_name: career-prediction-web-proxy
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/ssl:/etc/nginx/ssl
    restart: unless-stopped

  streamlit:
    build: ./streamlit_app
    image: career-prediction-streamlit:latest
    container_name: career-prediction-streamlit
    depends_on:
      - app
    environment:
      - BACKEND_URL=http://app:8080
      - STREAMLIT_SERVER_BASE_URL=/streamlit/
    restart: unless-stopped

  worker:
    build: ./app/
    image: career-prediction-worker:latest
    command: uv run python -u worker.py
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
    volumes:
      - ./app:/app
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: career-prediction-rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      retries: 5
      start_period: 10s
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    restart: on-failure
    
  database:
    image: postgres:15
    container_name: career-prediction-database
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  dbdata:
  rabbitmq-data:
